export const SOUND_CATEGORIES = {
  ALL: "All",
  NATURE: "Nature",
  URBAN: "Urban",
  AMBIENT: "Ambient",
  SLEEP: "Sleep",
} as const;

export type SoundCategory =
  (typeof SOUND_CATEGORIES)[keyof typeof SOUND_CATEGORIES];

export const WHITE_NOISE_SOUNDS = [
  {
    id: 0,
    name: "White Noise",
    description: "Classic white noise for focus and sleep",
    icon: "radio-outline",
    color: "#6366f1",
    source: require("../assets/sounds/60/white-noise-60.mp3"),
    premium: false, // Free sound
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 1,
    name: "Blender",
    description: "Steady kitchen blender hum for masking noise",
    icon: "cafe-outline",
    color: "#ef4444",
    source: require("../assets/sounds/60/blender-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 2,
    name: "Boiling",
    description: "Gentle bubbling water for calm focus",
    icon: "flame-outline",
    color: "#f59e0b",
    source: require("../assets/sounds/60/boiling-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 3,
    name: "Dryer",
    description: "Warm dryer rumble for cozy background noise",
    icon: "shirt-outline",
    color: "#eab308",
    source: require("../assets/sounds/60/dryer-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 4,
    name: "Fan",
    description: "Steady fan noise for concentration",
    icon: "refresh-outline",
    color: "#8b5cf6",
    source: require("../assets/sounds/60/fan-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 5,
    name: "Fridge",
    description: "Low fridge hum for subtle ambient sound",
    icon: "snow-outline",
    color: "#3b82f6",
    source: require("../assets/sounds/60/fridge-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 6,
    name: "Heater",
    description: "Soft heater noise for warmth and comfort",
    icon: "thermometer-outline",
    color: "#f97316",
    source: require("../assets/sounds/60/heater-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 7,
    name: "Hoover",
    description: "Vacuum cleaner hum for steady masking noise",
    icon: "leaf-outline",
    color: "#22c55e",
    source: require("../assets/sounds/60/hoover-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 8,
    name: "Motor",
    description: "Engine hum for industrial ambience",
    icon: "construct-outline",
    color: "#6b7280",
    source: require("../assets/sounds/60/motor-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 9,
    name: "Ocean Waves",
    description: "Soothing ocean waves for sleep",
    icon: "water-outline",
    color: "#06b6d4",
    source: require("../assets/sounds/60/ocean-60.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 10,
    name: "Rain",
    description: "Gentle rain sounds for relaxation",
    icon: "rainy-outline",
    color: "#3b82f6",
    source: require("../assets/sounds/60/rain-60.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 11,
    name: "Shower",
    description: "Soft shower stream for calm focus",
    icon: "water-outline",
    color: "#0ea5e9",
    source: require("../assets/sounds/60/shower-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 12,
    name: "Thunderstorm",
    description: "Powerful thunder and rain",
    icon: "thunderstorm-outline",
    color: "#6b7280",
    source: require("../assets/sounds/60/storm-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 13,
    name: "Stream",
    description: "Trickling stream for natural relaxation",
    icon: "leaf-outline",
    color: "#16a34a",
    source: require("../assets/sounds/60/stream-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 14,
    name: "Train",
    description: "Rhythmic train sounds for steady focus",
    icon: "train-outline",
    color: "#fbbf24",
    source: require("../assets/sounds/60/train-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 15,
    name: "Waves",
    description: "Gentle shoreline waves for sleep",
    icon: "water-outline",
    color: "#0ea5e9",
    source: require("../assets/sounds/60/waves-60.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.NATURE,
  },
  // Additional Nature Sounds
  {
    id: 16,
    name: "Forest",
    description: "Peaceful forest sounds with birds and wind",
    icon: "leaf-outline",
    color: "#22c55e",
    source: require("../assets/sounds/60/forest-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 17,
    name: "Birds",
    description: "Morning bird songs for natural awakening",
    icon: "bird-outline",
    color: "#fbbf24",
    source: require("../assets/sounds/60/birds-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 18,
    name: "Wind",
    description: "Gentle wind through trees for meditation",
    icon: "cloud-outline",
    color: "#94a3b8",
    source: require("../assets/sounds/60/wind-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  {
    id: 19,
    name: "Waterfall",
    description: "Powerful waterfall for deep relaxation",
    icon: "water-outline",
    color: "#06b6d4",
    source: require("../assets/sounds/60/waterfall-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
  },
  // Additional Urban Sounds
  {
    id: 20,
    name: "Traffic",
    description: "City traffic hum for urban focus",
    icon: "car-outline",
    color: "#6b7280",
    source: require("../assets/sounds/60/traffic-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 21,
    name: "Construction",
    description: "Construction site sounds for concentration",
    icon: "hammer-outline",
    color: "#f97316",
    source: require("../assets/sounds/60/construction-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 22,
    name: "Office",
    description: "Office background noise for productivity",
    icon: "business-outline",
    color: "#3b82f6",
    source: require("../assets/sounds/60/office-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  {
    id: 23,
    name: "Airport",
    description: "Airport announcements and activity",
    icon: "airplane-outline",
    color: "#8b5cf6",
    source: require("../assets/sounds/60/airport-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
  },
  // Additional Ambient Sounds
  {
    id: 24,
    name: "Brown Noise",
    description: "Deep brown noise for intense focus",
    icon: "radio-outline",
    color: "#92400e",
    source: require("../assets/sounds/60/brown-noise-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 25,
    name: "Pink Noise",
    description: "Balanced pink noise for gentle masking",
    icon: "radio-outline",
    color: "#ec4899",
    source: require("../assets/sounds/60/pink-noise-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 26,
    name: "Air Conditioning",
    description: "Cool AC hum for climate control",
    icon: "snow-outline",
    color: "#0ea5e9",
    source: require("../assets/sounds/60/air-conditioning-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  {
    id: 27,
    name: "Ventilation",
    description: "Subtle ventilation system noise",
    icon: "refresh-outline",
    color: "#64748b",
    source: require("../assets/sounds/60/ventilation-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
  },
  // Sleep-Focused Sounds
  {
    id: 28,
    name: "Crickets",
    description: "Summer night crickets for sleep",
    icon: "bug-outline",
    color: "#16a34a",
    source: require("../assets/sounds/60/crickets-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.SLEEP,
  },
  {
    id: 29,
    name: "Heartbeat",
    description: "Gentle heartbeat rhythm for comfort",
    icon: "heart-outline",
    color: "#ef4444",
    source: require("../assets/sounds/60/heartbeat-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.SLEEP,
  },
  {
    id: 30,
    name: "Lullaby",
    description: "Soft lullaby melody for babies",
    icon: "musical-notes-outline",
    color: "#f59e0b",
    source: require("../assets/sounds/60/lullaby-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.SLEEP,
  },
  {
    id: 31,
    name: "Tibetan Bowl",
    description: "Tibetan singing bowl for meditation",
    icon: "radio-outline",
    color: "#a855f7",
    source: require("../assets/sounds/60/tibetan-bowl-60.mp3"),
    premium: true,
    category: SOUND_CATEGORIES.SLEEP,
  },
];
