export const SOUND_CATEGORIES = {
  ALL: "All",
  NATURE: "Nature",
  URBAN: "Urban",
  AMBIENT: "Ambient",
  SLEEP: "Sleep",
} as const;

export const CATEGORY_COLORS = {
  [SOUND_CATEGORIES.ALL]: "#6366f1",
  [SOUND_CATEGORIES.NATURE]: "#3b82f6",
  [SOUND_CATEGORIES.URBAN]: "#6b7280",
  [SOUND_CATEGORIES.AMBIENT]: "#06b6d4",
  [SOUND_CATEGORIES.SLEEP]: "#f59e0b",
} as const;

export type SoundCategory =
  (typeof SOUND_CATEGORIES)[keyof typeof SOUND_CATEGORIES];

export const WHITE_NOISE_SOUNDS = [
  // Free local sounds
  {
    id: 0,
    name: "White Noise",
    description: "Classic white noise for focus and sleep",
    icon: "radio-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: require("../assets/sounds/white-noise.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: true,
  },
  {
    id: 1,
    name: "Rain",
    description: "Gentle rain sounds for relaxation",
    icon: "rainy-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: require("../assets/sounds/rain.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: true,
  },
  {
    id: 2,
    name: "Ocean",
    description: "Soothing ocean waves for sleep",
    icon: "water-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: require("../assets/sounds/ocean.mp3"),
    premium: false,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: true,
  },

  // Premium sounds - require download
  {
    id: 3,
    name: "Air Conditioning",
    description: "Cool AC hum for climate control",
    icon: "snow-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: "https://slumbr.space/sounds/air-conditioning.mp3",
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: false,
  },
  {
    id: 4,
    name: "Airport",
    description: "Airport announcements and activity",
    icon: "airplane-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/airport.mp3",
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 5,
    name: "Birds",
    description: "Morning bird songs for natural awakening",
    icon: "sunny-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/birds.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 6,
    name: "Brown Noise",
    description: "Deep brown noise for intense focus",
    icon: "radio-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: "https://slumbr.space/sounds/brown-noise.mp3",
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: false,
  },
  {
    id: 7,
    name: "Crickets",
    description: "Summer night crickets for sleep",
    icon: "bug-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.SLEEP],
    source: "https://slumbr.space/sounds/crickets.mp3",
    premium: true,
    category: SOUND_CATEGORIES.SLEEP,
    isLocal: false,
  },
  {
    id: 8,
    name: "Dishwasher",
    description: "Steady dishwasher hum for masking noise",
    icon: "cafe-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/dishwasher.mp3",
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 9,
    name: "Driving Rain",
    description: "Heavy rain sounds for deep relaxation",
    icon: "rainy-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/driving-rain.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 10,
    name: "Fan",
    description: "Steady fan noise for concentration",
    icon: "refresh-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: "https://slumbr.space/sounds/fan.mp3",
    premium: false,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: false,
  },
  {
    id: 11,
    name: "Forest",
    description: "Peaceful forest sounds with birds and wind",
    icon: "leaf-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/forest.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 12,
    name: "Fridge",
    description: "Low fridge hum for subtle ambient sound",
    icon: "snow-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/fridge.mp3",
    premium: false,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 13,
    name: "Hair Dryer",
    description: "Hair dryer hum for steady masking noise",
    icon: "leaf-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/hair-dryer.mp3",
    premium: false,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 14,
    name: "Heartbeat",
    description: "Gentle heartbeat rhythm for comfort",
    icon: "heart-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.SLEEP],
    source: "https://slumbr.space/sounds/heartbeat.mp3",
    premium: false,
    category: SOUND_CATEGORIES.SLEEP,
    isLocal: false,
  },
  {
    id: 15,
    name: "Heater",
    description: "Soft heater noise for warmth and comfort",
    icon: "thermometer-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: "https://slumbr.space/sounds/heater.mp3",
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: false,
  },
  {
    id: 16,
    name: "Office",
    description: "Office background noise for productivity",
    icon: "business-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/office.mp3",
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 17,
    name: "Pink Noise",
    description: "Balanced pink noise for gentle masking",
    icon: "radio-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.AMBIENT],
    source: "https://slumbr.space/sounds/pink-noise.mp3",
    premium: true,
    category: SOUND_CATEGORIES.AMBIENT,
    isLocal: false,
  },
  {
    id: 18,
    name: "Sprinkler",
    description: "Garden sprinkler for outdoor ambience",
    icon: "water-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/sprinkler.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 19,
    name: "Storm",
    description: "Powerful thunderstorm for deep sleep",
    icon: "thunderstorm-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/storm.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 20,
    name: "Stream",
    description: "Trickling stream for natural relaxation",
    icon: "leaf-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/stream.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 21,
    name: "Thunder",
    description: "Rolling thunder for dramatic ambience",
    icon: "thunderstorm-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/thunder.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
  {
    id: 22,
    name: "Train",
    description: "Rhythmic train sounds for steady focus",
    icon: "train-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.URBAN],
    source: "https://slumbr.space/sounds/train.mp3",
    premium: true,
    category: SOUND_CATEGORIES.URBAN,
    isLocal: false,
  },
  {
    id: 23,
    name: "Wind",
    description: "Gentle wind through trees for meditation",
    icon: "cloud-outline",
    color: CATEGORY_COLORS[SOUND_CATEGORIES.NATURE],
    source: "https://slumbr.space/sounds/wind.mp3",
    premium: true,
    category: SOUND_CATEGORIES.NATURE,
    isLocal: false,
  },
];
